name: Lint Code (Golint)

on: push

permissions:
  contents: read

defaults:
  run:
    working-directory: ./

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.39.0'

      - name: Run GolangCILint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          install-mode: goinstall
