name: Run Tests (Jest)

on: push

permissions:
  contents: read

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Runner Common Setup
        uses: mridang/action-runner-common@v1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.39.0'

      - name: Run Tests
        run: make test
